const express = require('express');
const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());

app.get('/', (req, res) => {
    res.send('<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>GenZTrending</title><script src="https://tailwindcss.com"></script></head><body class="bg-[#06090e] text-white min-h-screen flex flex-col justify-between"><header class="p-5 border-b border-gray-900 bg-[#06090e]"><div class="container mx-auto flex justify-between items-center"><h1 class="text-xl font-bold text-[#00ff66] tracking-wider cursor-pointer">GENZTRENDING</h1><div class="flex items-center space-x-6"><button onclick="alert(\'Welcome! Processing Demo Mode...\'); document.getElementById(\'terminal\').style.display=\'block\'; document.getElementById(\'landing\').style.display=\'none\';" class="bg-[#00ff66] text-black font-bold px-4 py-2 rounded-full text-sm">Try Demo</button></div></div></header><main class="container mx-auto px-6 flex-grow flex flex-col justify-center my-8"><div id="landing" class="text-center max-w-2xl mx-auto py-12"><h2 class="text-4xl md:text-6xl font-extrabold text-white mb-6">Trading Made Easy, <br><span class="text-[#00ff66]">Trade Smart</span></h2><p class="text-gray-400 text-lg mb-10">The best Trusted Binary Automated trading platform with fast withdrawals.</p><button onclick="alert(\'Welcome! Processing Demo Mode...\'); document.getElementById(\'terminal\').style.display=\'block\'; document.getElementById(\'landing\').style.display=\'none\';" class="bg-[#00ff66] text-black font-bold px-8 py-3.5 rounded-full text-sm">Get Started – It\'s Free →</button></div><div id="terminal" class="max-w-5xl mx-auto w-full" style="display:none;"><div class="p-6 rounded-lg bg-[#0d1117] border border-[#00ff66]/30 mb-8"><h2 class="text-xl font-semibold text-white">FX Markets Are Live</h2><p class="text-gray-400">Welcome inside your trading terminal ($3,000.00 Demo Balance Loaded).</p></div><div class="mb-8 p-4 rounded-lg bg-[#0d1117] border border-gray-800"><h3 class="text-lg font-semibold text-white mb-4">Live Advanced Forex Chart</h3><div style="height: 450px; width:100%"><div id="tradingview_chart" style="height:100%; width:100%"></div><script type="text/javascript" src="https://tradingview.com"></script><script type="text/javascript">new TradingView.widget({"width": "100%", "height": "100%", "symbol": "FX:EURUSD", "interval": "15", "theme": "dark", "style": "1", "locale": "en", "container_id": "tradingview_chart"});</script></div></div></div></main><footer class="p-6 text-center text-xs text-gray-600 border-t border-gray-950 bg-[#0d1117]"><p>&copy; 2026 GenZTrending FX. All rights reserved.</p></footer></body></html>');
});

app.listen(PORT, () => {
    console.log("Server running on port " + PORT);
});
